# Generated by Django 4.2.7 on 2023-11-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_news_body_alter_news_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='view_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
