# Generated by Django 4.2.7 on 2023-11-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_news_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
